### ISSUE TITLE
[Issue] Checkstyle is not working

### ISSUE THREAD

**Issue by Marco-Ivantschitz** [Marco-Ivantschitz/fh-burgenland-bswe-3b-2at#30]
### Description

As already discussed by email, I have now created an issue for my checkstyle problem. Please find attached the files:

[Checkstyle Datei] https://github.com/Marco-Ivantschitz/fh-burgenland-bswe-3b-2at/blob/main/config/checkstyle/checkstyle.xml

[build.gradle Datei] https://github.com/Marco-Ivantschitz/fh-burgenland-bswe-3b-2at/blob/main/build.gradle

**Comment by muhlba91** [comment]
1/ Can you run the checkstyle command with `--stacktrace`? this shoulf let you know more information on where exactly this happens.

2/ is there any reason why you changed the source compatibility to java 17 and not leave it at 21?

**Comment by Marco-Ivantschitz** [comment]
1/when i use the command **./gradlew checkstyleMain checkstyleTest --stacktrace** this error message comes:  **Bitte pr├╝fen Sie, dass der Klassenname als kanonischer Name a
ngegeben wurde oder lesen Sie, wie Sie abgek├╝rzte Namen konfigurieren: https://checkstyle.org/config.html#Packages.**

It seems that with the OverrideAnnotation in the TreeWalker module in the Checkstyle file it does not work

2/ when i use java 21 with the ./gradlew checkstyleMain checkstyleTest command i always get this error:  Fehler: Ung├╝ltiges Quellrelease: 21. Therefore i use Java 17

i wrote some extra code in the build.gradle file but i changed it back to the original.

When i build gradl and use the command: ./gradlew checkstyleMain checkstyleTest without the OverrideAnnotation in the TreeWalker i do not get any errors and it works fine. So is there somwthing wrong with the OverrideAnnotation?

**Comment by muhlba91** [comment]
yes, i think the problem is found. 😉 
i didn't see this line you added but i'd suggest you double-check in the checkstyle documentation how this rule is named and added to the config file.

as for 21 vs. 17: i assume you use java < 21 locally in your computer (and/or as java_home).

**Comment by Marco-Ivantschitz** [comment]
yes, i found the problem. Thank you very much for the help.

Last question for this topic. Would it be a problem, if i use Java 17 or should I use Java 21

**Comment by muhlba91** [comment]
let's say if you were to change it to java 17 you'd really need a good justification for it. 😉 

simply said: imagine you get onto the product team as an engineer and the product is working and running for years and is already in production as well.

**Comment by Marco-Ivantschitz** [comment]
I changend it to Java 21. I found the Issue. It was the system variable JAVA_HOME. For the system variable was the path to jdk19 instead of jdk21. So now it works with Java 21
